# This is a basic workflow to help you get started with Actions

name: clone

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Create initial Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            cd /pub/${{secrets.USERNAME}}
            git clone git@github.com/jpsphaxer/cmsc389T-web-template.git
